name: Verify the Site Builds

on:
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install and Build 🔧
      run: |
        yarn install
        yarn docs:build